apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bankapp.fullname" . }}
  labels:
    {{- include "bankapp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bankapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bankapp.labels" . | nindent 8 }}
    spec:
      volumes:
        - name: bank-app-config
          configMap:
            name: bank-app-config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe: {{ toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe: {{ toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}   
          volumeMounts:
            - name: bank-app-config
              mountPath: /app/config/application.properties
              subPath: application.properties
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "file:/app/config/application.properties"
  
