apiVersion: v1
kind: Service
metadata:
  name: ecommerce-site
spec:
  type: ClusterIP
  selector:
    app: ecommerce-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 

